package test

import (
	"fmt"
	"slices"
	"strings"
	"testing"

	"github.com/xo/dbmeta"
	rsfixture "github.com/xo/dbmeta/models/redshift/fixture"
)

// TestRedshiftAccessReadBack reads the kinds that D204 added as typed values,
// as the administrator, against the grants the fixture makes.
func TestRedshiftAccessReadBack(t *testing.T) {
	db := openRedshift(t)
	m := setupRedshift(t, db)
	schema := rsfixture.Everything.Schema

	t.Run("privileges", func(t *testing.T) {
		got := byName(readAll(t, dbmeta.Privileges, m, db, dbmeta.Args{Schema: schema}.Map()),
			func(v dbmeta.Privilege) string { return v.Name })
		if v := got["author"]; v.Type != "table" || !v.Access.Valid || !strings.Contains(v.Access.V, "group dbmeta_fixture_group=r/") {
			t.Errorf("expected the grant to the group in the access of author, got %+v", v)
		}
		if v := got["recent"]; v.Type != "view" {
			t.Errorf("expected recent to be a view, got %+v", v)
		}
	})

	t.Run("column privileges", func(t *testing.T) {
		got := readAll(t, dbmeta.ColumnPrivileges, m, db, dbmeta.Args{Schema: schema}.Map())
		if len(got) != 1 {
			t.Fatalf("expected one column grant, got %+v", got)
		}
		v := got[0]
		if v.Table != "book" || v.Column != "title" || v.Ordinal != 3 || v.Privileges != "SELECT" ||
			v.Access != "group dbmeta_fixture_group=SELECT" || v.Grantee.V != "dbmeta_fixture_group" {
			t.Errorf("expected the grant of SELECT on book.title to the group, got %+v", v)
		}
	})

	t.Run("role grants", func(t *testing.T) {
		got := readAll(t, dbmeta.RoleGrants, m, db, dbmeta.Args{Name: "dbmeta_fixture_%"}.Map())
		if len(got) != 1 || got[0].Role != "dbmeta_fixture_member" || got[0].MemberOf != "dbmeta_fixture_role" {
			t.Errorf("expected the member role to hold the role, got %+v", got)
		}
	})

	t.Run("default acls", func(t *testing.T) {
		got := readAll(t, dbmeta.DefaultACLs, m, db, dbmeta.Args{Schema: schema}.Map())
		if len(got) != 1 || got[0].Type != "table" || !strings.Contains(got[0].Access.V, "group dbmeta_fixture_group=r/") {
			t.Errorf("expected the default grant to the group, got %+v", got)
		}
	})

	t.Run("roles", func(t *testing.T) {
		got := byName(readAll(t, dbmeta.Roles, m, db, dbmeta.Args{Name: "dbmeta_fixture_%"}.Map()),
			func(v dbmeta.Role) string { return v.Name })
		for _, name := range []string{"dbmeta_fixture_role", "dbmeta_fixture_member", "dbmeta_fixture_group"} {
			if v, ok := got[name]; !ok || v.CanLogin {
				t.Errorf("expected %s to be listed and unable to log in, got %+v", name, v)
			}
		}
		admin := readAll(t, dbmeta.Roles, m, db, dbmeta.Args{Name: "admin"}.Map())
		if len(admin) != 1 || !admin[0].CanLogin || !admin[0].Superuser {
			t.Errorf("expected the administrator to be a superuser that can log in, got %+v", admin)
		}
	})

	t.Run("languages", func(t *testing.T) {
		got := byName(readAll(t, dbmeta.Languages, m, db, dbmeta.Args{}.Map()),
			func(v dbmeta.Language) string { return v.Name })
		if v, ok := got["plpgsql"]; !ok || v.Internal || v.Handler == "" {
			t.Errorf("expected plpgsql with a call handler, got %+v", v)
		}
	})

	t.Run("settings", func(t *testing.T) {
		got := readAll(t, dbmeta.Settings, m, db, dbmeta.Args{Name: "search_path"}.Map())
		if len(got) != 1 || !got[0].Value.Valid || got[0].Display.V != got[0].Value.V {
			t.Errorf("expected search_path with a value, got %+v", got)
		}
	})

	t.Run("constraint columns", func(t *testing.T) {
		got := readAll(t, dbmeta.ConstraintColumns, m, db, dbmeta.Args{Schema: schema, Parent: "shipment"}.Map())
		var fk []string
		for _, v := range got {
			if v.Constraint == "shipment_country_fkey" {
				fk = append(fk, fmt.Sprintf("%d %s -> %s.%s", v.Ordinal, v.Name, v.ForeignTable.V, v.ForeignName.V))
			}
		}
		want := []string{"1 country -> region.country", "2 area -> region.area"}
		if !slices.Equal(fk, want) {
			t.Errorf("expected %v, got %v", want, fk)
		}
	})
}

// TestRedshiftColumnsMeasured reads the columns that D204 measured with a
// scratch table: the identity kinds, the collation, the comment and the
// default. The table goes with the fixture schema.
func TestRedshiftColumnsMeasured(t *testing.T) {
	db := openRedshift(t)
	m := setupRedshift(t, db)
	schema := rsfixture.Everything.Schema
	exec(t, db, `CREATE TABLE `+schema+`.scratch (
	always_id BIGINT IDENTITY(10, 3),
	default_id BIGINT GENERATED BY DEFAULT AS IDENTITY (5, 2),
	plain INTEGER,
	label VARCHAR(10) DEFAULT 'x',
	folded VARCHAR(10) COLLATE CASE_INSENSITIVE,
	noted INTEGER NOT NULL
)`)
	exec(t, db, `COMMENT ON COLUMN `+schema+`.scratch.noted IS 'a note'`)
	got := byName(readAll(t, dbmeta.Columns, m, db, dbmeta.Args{Schema: schema, Parent: "scratch"}.Map()),
		func(v dbmeta.Column) string { return v.Name })
	if v := got["always_id"]; v.Identity.V != "a" || !strings.HasPrefix(v.Default.V, `"identity"(`) {
		t.Errorf("expected the identity kind a, got %+v", v)
	}
	if v := got["default_id"]; v.Identity.V != "d" || !strings.HasPrefix(v.Default.V, "default_identity(") {
		t.Errorf("expected the identity kind d, got %+v", v)
	}
	if v := got["plain"]; v.Identity.V != "" || v.Collation.Valid {
		t.Errorf("expected no identity and no collation for an integer, got %+v", v)
	}
	if v := got["label"]; v.Identity.V != "" || v.Collation.V != "case_sensitive" {
		t.Errorf("expected case_sensitive for a plain character column, got %+v", v)
	}
	if v := got["folded"]; v.Collation.V != "case_insensitive" {
		t.Errorf("expected case_insensitive, got %+v", v)
	}
	if v := got["noted"]; v.Comment.V != "a note" || v.Nullable {
		t.Errorf("expected the comment and NOT NULL, got %+v", v)
	}
	// The kind a means that an INSERT cannot name the column, which the
	// server confirms with this refusal. The kind d accepts a value.
	_, err := db.ExecContext(t.Context(), `INSERT INTO `+schema+`.scratch (always_id) VALUES (1)`)
	if err == nil || !strings.Contains(err.Error(), "cannot set an identity column to a value") {
		t.Errorf("expected the server to refuse a value for an always identity column, got %v", err)
	}
	exec(t, db, `INSERT INTO `+schema+`.scratch (default_id, noted) VALUES (99, 1)`)
	// The conformance section has no check constraint, because Redshift
	// refuses CHECK in a table definition.
	_, err = db.ExecContext(t.Context(), `CREATE TABLE `+schema+`.checked (a INTEGER CHECK (a > 0))`)
	if err == nil {
		t.Error("expected the server to refuse a CHECK constraint")
	} else {
		t.Logf("the server answers a CHECK constraint with: %v", err)
	}
}
