// Package fixture holds a known good schema for a database read through
// information_schema.
//
// It is the counterpart of the PostgreSQL fixture, and it exists for the same
// reason: a query that has never run against a real server is not finished,
// and running one needs a schema with something in it to find.
//
// This fixture is harder than a native one, because it must build on every
// database that has an information_schema and those disagree about syntax. It
// therefore carries alternatives per dialect rather than per version, which is
// the one place a shared model differs from a native one.
//
// Like every fixture here it is additive. A later release may add an object
// and will not rename or remove one.
package fixture

// Syntax holds the dialect differences a fixture statement needs.
//
// A native fixture varies by version, because one database changed over time.
// A shared fixture varies by dialect as well, because the databases never
// agreed in the first place. These are the pieces they disagree about.
type Syntax struct {
	// Serial is how the database declares a generated key. PostgreSQL writes
	// serial, MySQL writes int AUTO_INCREMENT, SQL Server writes int IDENTITY.
	Serial string
	// Text is the type for a string of any length. Several databases have no
	// unbounded text type usable in an index, so this is often varchar(255).
	Text string
	// CreateSchema creates a schema, and DropSchema drops it. MySQL treats a
	// schema and a database as the same thing.
	CreateSchema string
	DropSchema   string
	// HasSequences says whether CREATE SEQUENCE works, which matches the
	// [informationschema.Sequences] feature.
	HasSequences bool
	// HasCheckConstraints says whether a check constraint is recorded, which
	// matches the [informationschema.CheckConstraints] feature.
	HasCheckConstraints bool
}

// Standard is the syntax of a database that follows the SQL standard closely.
func Standard() Syntax {
	return Syntax{
		Serial:              "integer GENERATED BY DEFAULT AS IDENTITY",
		Text:                "varchar(255)",
		CreateSchema:        "CREATE SCHEMA dbmeta_fixture",
		DropSchema:          "DROP SCHEMA dbmeta_fixture CASCADE",
		HasSequences:        true,
		HasCheckConstraints: true,
	}
}

// PostgreSQL is the syntax PostgreSQL takes.
//
// It uses serial rather than the standard identity column, because identity
// arrived in release 10 and dbmeta supports 9.6. A shared fixture cannot
// assume the standard spelling works: the databases that have an
// information_schema implement different amounts of the standard, and the
// oldest supported release of one of them implements less than it does today.
func PostgreSQL() Syntax {
	s := Standard()
	s.Serial = "serial"
	s.Text = "text"
	return s
}

// MySQL is the syntax MySQL and MariaDB take. A schema is a database, there
// are no sequences, and a generated key is an auto increment.
//
// Check constraints are off here to match the profile that `usql` uses for the
// same databases. MariaDB from 10.2 and MySQL from 8.0.16 do record them, so
// when the real `mysql` model lands this and its profile may both turn on.
// They must turn on together, which is what
// TestFixtureMatchesTheProfile enforces: a fixture must not build an object
// the model will not read.
func MySQL() Syntax {
	s := Standard()
	s.Serial = "integer AUTO_INCREMENT"
	s.CreateSchema = "CREATE SCHEMA dbmeta_fixture"
	s.DropSchema = "DROP SCHEMA dbmeta_fixture"
	s.HasSequences = false
	s.HasCheckConstraints = false
	return s
}

// Everything returns a schema holding one of every object that
// information_schema describes, in the syntax the database takes.
//
// It is smaller than the PostgreSQL fixture because information_schema is
// smaller. It answers for tables, columns, constraints, routines, sequences
// and privileges, and knows nothing of the thirty other object kinds that
// `psql` describes.
func Everything(syn Syntax) Fixture {
	steps := []Step{
		{"schema", syn.CreateSchema},
		{"author table", `CREATE TABLE dbmeta_fixture.author (
	author_id ` + syn.Serial + ` PRIMARY KEY,
	name ` + syn.Text + ` NOT NULL,
	rating integer
)`},
		{"book table", `CREATE TABLE dbmeta_fixture.book (
	book_id ` + syn.Serial + ` PRIMARY KEY,
	author_id integer NOT NULL,
	title ` + syn.Text + ` NOT NULL,
	published date,
	CONSTRAINT book_author_fk FOREIGN KEY (author_id) REFERENCES dbmeta_fixture.author(author_id),
	CONSTRAINT book_title_unique UNIQUE (title)
)`},
		{"view", `CREATE VIEW dbmeta_fixture.recent AS
	SELECT book_id, title FROM dbmeta_fixture.book WHERE published IS NOT NULL`},
	}
	if syn.HasCheckConstraints {
		steps = append(steps, Step{"check constraint",
			`ALTER TABLE dbmeta_fixture.book ADD CONSTRAINT title_not_empty CHECK (title <> '')`})
	}
	if syn.HasSequences {
		steps = append(steps, Step{"sequence",
			`CREATE SEQUENCE dbmeta_fixture.counter START WITH 10 INCREMENT BY 2`})
	}
	return Fixture{
		Name:     "everything",
		Schema:   "dbmeta_fixture",
		Setup:    steps,
		Teardown: []Step{{"drop schema", syn.DropSchema}},
	}
}

// Step is one statement of a fixture.
//
// A shared fixture resolves its dialect differences when it is built, in
// [Everything], rather than when it is run, so a step is plain SQL by the time
// a caller sees it. A native fixture keeps its alternatives until run time
// because it varies by server version, which is not known until a connection
// exists.
type Step struct {
	Name string
	SQL  string
}

// Fixture is a schema, with the statements that build it and drop it.
type Fixture struct {
	Name     string
	Schema   string
	Setup    []Step
	Teardown []Step
}
