package fixture_test

import (
	"strings"
	"testing"

	is "github.com/xo/dbmeta/models/informationschema"
	"github.com/xo/dbmeta/models/informationschema/fixture"
)

// TestSyntaxVariesByDialect is the difference between a shared fixture and a
// native one. A native fixture varies by version because one database changed.
// A shared one varies by dialect because the databases never agreed.
func TestSyntaxVariesByDialect(t *testing.T) {
	t.Parallel()
	std := fixture.Everything(fixture.Standard())
	my := fixture.Everything(fixture.MySQL())

	find := func(f fixture.Fixture, name string) string {
		t.Helper()
		for _, s := range f.Setup {
			if s.Name == name {
				return s.SQL
			}
		}
		return ""
	}
	if got := find(std, "author table"); !strings.Contains(got, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Errorf("expected the standard generated key:\n%s", got)
	}
	if got := find(my, "author table"); !strings.Contains(got, "AUTO_INCREMENT") {
		t.Errorf("expected the MySQL generated key:\n%s", got)
	}
}

// TestFixtureMatchesTheProfile is the rule that keeps the two halves honest. A
// fixture must not build an object the model will not read, and must build
// every object it will.
func TestFixtureMatchesTheProfile(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		syntax  fixture.Syntax
		profile is.Profile
	}{
		{"standard", fixture.Standard(), is.Profile{}},
		{"mysql", fixture.MySQL(), is.Profile{
			Has: is.Standard().Without(is.Sequences, is.CheckConstraints),
		}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			f := fixture.Everything(test.syntax)
			built := map[string]bool{}
			for _, s := range f.Setup {
				built[s.Name] = true
			}
			has := func(feature is.Feature) bool {
				if test.profile.Has == nil {
					return is.Standard().Has(feature)
				}
				return test.profile.Has.Has(feature)
			}
			if built["sequence"] != has(is.Sequences) {
				t.Errorf("the fixture builds a sequence %v and the profile reads one %v",
					built["sequence"], has(is.Sequences))
			}
			if built["check constraint"] != has(is.CheckConstraints) {
				t.Errorf("the fixture builds a check constraint %v and the profile reads one %v",
					built["check constraint"], has(is.CheckConstraints))
			}
		})
	}
}

// TestEverythingIsInOneSchema checks that a caller can read one schema to see
// the whole fixture and drop one to remove it.
func TestEverythingIsInOneSchema(t *testing.T) {
	t.Parallel()
	for _, syn := range []fixture.Syntax{fixture.Standard(), fixture.MySQL()} {
		f := fixture.Everything(syn)
		if f.Schema == "" {
			t.Fatal("expected a schema name")
		}
		for _, s := range f.Setup {
			if !strings.Contains(s.SQL, f.Schema) {
				t.Errorf("%q does not name the fixture schema:\n%s", s.Name, s.SQL)
			}
		}
		if len(f.Teardown) == 0 {
			t.Error("expected a teardown")
		}
	}
}
